### PR TITLE
Add option to use in-memory FS for pebble

### PR DESCRIPTION
**Pull request by carsonip**
Implemented as a boolean config to avoid exposing pebble internals / config to users.

### CODE REVIEW

**Review by marclop — APPROVED** [review]
Did you run any tests with the memory vfs?

**Comment by carsonip** [comment]
> Did you run any tests with the memory vfs?

I manually ran TestAggregateAndHarvest and it works ok. I ran the benchmarks with memory vfs for inmemoryfs-after.

benchstat:
```
goos: linux
goarch: amd64
pkg: github.com/elastic/apm-aggregation/aggregators
cpu: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
                            │ bench-out/inmemoryfs-before │     bench-out/inmemoryfs-after      │
                            │           sec/op            │    sec/op     vs base               │
AggregateCombinedMetrics-16                   3.434µ ± 4%    3.213µ ± 4%   -6.41% (p=0.004 n=6)
AggregateBatchSerial-16                       13.95µ ± 6%    13.22µ ± 8%        ~ (p=0.180 n=6)
AggregateBatchParallel-16                     14.26µ ± 2%    15.20µ ± 9%   +6.64% (p=0.026 n=6)
CombinedMetricsEncoding-16                    5.218µ ± 4%    5.177µ ± 2%        ~ (p=0.310 n=6)
CombinedMetricsDecoding-16                    4.327µ ± 1%    4.961µ ± 4%  +14.64% (p=0.002 n=6)
CombinedMetricsToBatch-16                     431.9µ ± 6%    425.2µ ± 2%        ~ (p=0.065 n=6)
EventToCombinedMetrics-16                     966.7n ± 5%   1130.5n ± 9%  +16.94% (p=0.002 n=6)
geomean                                       9.390µ         9.682µ        +3.11%

                            │ bench-out/inmemoryfs-before │      bench-out/inmemoryfs-after       │
                            │            B/op             │     B/op      vs base                 │
AggregateCombinedMetrics-16                3.443Ki ± 1%     3.878Ki ± 1%  +12.63% (p=0.002 n=6)
AggregateBatchSerial-16                    20.15Ki ± 0%     22.29Ki ± 1%  +10.62% (p=0.002 n=6)
AggregateBatchParallel-16                  20.10Ki ± 0%     22.60Ki ± 1%  +12.44% (p=0.002 n=6)
CombinedMetricsEncoding-16                   0.000 ± 0%       0.000 ± 0%        ~ (p=1.000 n=6) ¹
CombinedMetricsDecoding-16                 10.01Ki ± 0%     10.01Ki ± 0%        ~ (p=0.182 n=6)
geomean                                                 ²                  +6.97%               ²
¹ all samples are equal
² summaries must be >0 to compute geomean

                            │ bench-out/inmemoryfs-before │     bench-out/inmemoryfs-after     │
                            │          allocs/op          │ allocs/op   vs base                │
AggregateCombinedMetrics-16                  27.00 ± 4%     27.00 ± 4%       ~ (p=1.000 n=6)
AggregateBatchSerial-16                      94.00 ± 0%     94.00 ± 0%       ~ (p=1.000 n=6) ¹
AggregateBatchParallel-16                    94.00 ± 0%     94.00 ± 1%       ~ (p=1.000 n=6)
CombinedMetricsEncoding-16                   0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=6) ¹
CombinedMetricsDecoding-16                   40.00 ± 0%     40.00 ± 0%       ~ (p=1.000 n=6) ¹
geomean                                                 ²               +0.00%               ²
¹ all samples are equal
² summaries must be >0 to compute geomean
```

No idea why it affects EventToCombinedMetrics as it is not related to pebble at all.

**Comment by marclop** [comment]
Am I reading the results right? It appears to be slower with the in-memory VFS

**Comment by carsonip** [comment]
> Am I reading the results right? It appears to be slower with the in-memory VFS

The weird thing is that the performance drop cannot be observed when the affected benchmarks are run separately. It also doesn't make sense for them to have any performance hit because of in-memory VFS because BenchmarkCombinedMetricsDecoding does not touch anything about pebble.

I suspect it is gc (because the vfs requires memory allocations) causing noise to subsequent benchmarks.

**Comment by carsonip** [comment]
With NewMem and DisableWAL:
```
goos: linux
goarch: amd64
pkg: github.com/elastic/apm-aggregation/aggregators
cpu: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
                            │ bench-out/new-mem-and-disable-wal-2-before │ bench-out/new-mem-and-disable-wal-2-after │
                            │                   sec/op                   │       sec/op        vs base               │
AggregateCombinedMetrics-16                                  4.006µ ± 2%         3.901µ ± 25%       ~ (p=0.190 n=10)
AggregateBatchSerial-16                                     10.561µ ± 5%         9.969µ ±  3%  -5.61% (p=0.001 n=10)
AggregateBatchParallel-16                                    10.81µ ± 6%         10.55µ ±  6%       ~ (p=0.165 n=10)
CombinedMetricsEncoding-16                                   4.925µ ± 2%         5.061µ ±  4%  +2.77% (p=0.011 n=10)
CombinedMetricsDecoding-16                                   4.394µ ± 2%         4.563µ ±  8%  +3.83% (p=0.001 n=10)
CombinedMetricsToBatch-16                                    411.5µ ± 1%         418.9µ ±  1%  +1.80% (p=0.001 n=10)
EventToCombinedMetrics-16                                    837.3n ± 5%         877.9n ±  3%  +4.85% (p=0.004 n=10)
geomean                                                      8.576µ              8.602µ        +0.30%

                            │ bench-out/new-mem-and-disable-wal-2-before │ bench-out/new-mem-and-disable-wal-2-after │
                            │                    B/op                    │       B/op        vs base                 │
AggregateCombinedMetrics-16                               4.857Ki ± 0%         4.885Ki ± 2%       ~ (p=0.171 n=10)
AggregateBatchSerial-16                                   11.34Ki ± 0%         11.31Ki ± 0%       ~ (p=0.065 n=10)
AggregateBatchParallel-16                                 11.29Ki ± 1%         11.34Ki ± 1%       ~ (p=0.353 n=10)
CombinedMetricsEncoding-16                                  0.000 ± 0%           0.000 ± 0%       ~ (p=1.000 n=10) ¹
CombinedMetricsDecoding-16                                10.01Ki ± 0%         10.01Ki ± 0%       ~ (p=0.885 n=10)
CombinedMetricsToBatch-16                                 37.66Ki ± 0%         37.66Ki ± 0%       ~ (p=1.000 n=10) ¹
EventToCombinedMetrics-16                                   16.00 ± 0%           16.00 ± 0%       ~ (p=1.000 n=10) ¹
geomean                                                                ²                     +0.10%                ²
¹ all samples are equal
² summaries must be >0 to compute geomean

                            │ bench-out/new-mem-and-disable-wal-2-before │ bench-out/new-mem-and-disable-wal-2-after │
                            │                 allocs/op                  │    allocs/op      vs base                 │
AggregateCombinedMetrics-16                                 39.00 ± 0%           39.00 ± 3%       ~ (p=0.635 n=10)
AggregateBatchSerial-16                                     67.00 ± 0%           67.00 ± 1%       ~ (p=1.000 n=10)
AggregateBatchParallel-16                                   67.00 ± 0%           67.00 ± 0%       ~ (p=1.000 n=10)
CombinedMetricsEncoding-16                                  0.000 ± 0%           0.000 ± 0%       ~ (p=1.000 n=10) ¹
CombinedMetricsDecoding-16                                  40.00 ± 0%           40.00 ± 0%       ~ (p=1.000 n=10) ¹
CombinedMetricsToBatch-16                                   308.0 ± 0%           308.0 ± 0%       ~ (p=1.000 n=10) ¹
EventToCombinedMetrics-16                                   2.000 ± 0%           2.000 ± 0%       ~ (p=1.000 n=10) ¹
geomean                                                                ²                     +0.00%                ²
¹ all samples are equal
² summaries must be >0 to compute geomean
```

**Review by axw — APPROVED** [review]

**Review by lahsivjar — APPROVED** [review]

**Pull request merged**
